#!/usr/bin/env bash

# +----------+
# | Personal |
# +----------+

# Folders
alias work="$HOME/workspace"
alias doc="$HOME/Documents"
alias dow="$HOME/Downloads"
alias dot="$HOME/.dotfiles"
alias notes="/mnt/c/Users/dhruv/Documents/Notes"